/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.35
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package sml;

public enum smlRunState {
  sml_RUNSTATE_STOPPED,
  sml_RUNSTATE_INTERRUPTED,
  sml_RUNSTATE_RUNNING,
  sml_RUNSTATE_HALTED;

  public final int swigValue() {
    return swigValue;
  }

  public static smlRunState swigToEnum(int swigValue) {
    smlRunState[] swigValues = smlRunState.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (smlRunState swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + smlRunState.class + " with value " + swigValue);
  }

  private smlRunState() {
    this.swigValue = SwigNext.next++;
  }

  private smlRunState(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  private smlRunState(smlRunState swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

