/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.35
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package sml;

public class SWIGTYPE_p_f_sml__smlStringEventId_p_void_p_sml__Kernel_p_q_const__char__std__string {
  private long swigCPtr;

  protected SWIGTYPE_p_f_sml__smlStringEventId_p_void_p_sml__Kernel_p_q_const__char__std__string(long cPtr, boolean futureUse) {
    swigCPtr = cPtr;
  }

  protected SWIGTYPE_p_f_sml__smlStringEventId_p_void_p_sml__Kernel_p_q_const__char__std__string() {
    swigCPtr = 0;
  }

  protected static long getCPtr(SWIGTYPE_p_f_sml__smlStringEventId_p_void_p_sml__Kernel_p_q_const__char__std__string obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }
}

