package org.jsoar.util.db;

import java.io.InputStream;
import java.io.Reader;
import java.math.BigDecimal;
import java.net.URL;
import java.sql.Array;
import java.sql.Blob;
import java.sql.Clob;
import java.sql.Connection;
import java.sql.Date;
import java.sql.NClob;
import java.sql.ParameterMetaData;
import java.sql.PreparedStatement;
import java.sql.Ref;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.RowId;
import java.sql.SQLException;
import java.sql.SQLWarning;
import java.sql.SQLXML;
import java.sql.Time;
import java.sql.Timestamp;
import java.util.Calendar;
import java.util.HashMap;
import java.util.Map;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class SoarPreparedStatement implements PreparedStatement
{
    private static final Logger logger = LoggerFactory.getLogger(SoarPreparedStatement.class);
    
    private final PreparedStatement ps;
    private final String query;
    private final Map<Integer, Object> bindVariables = 
            new HashMap<Integer, Object>();
    
    
    public SoarPreparedStatement(PreparedStatement ps){
        this(ps, "");
    }
    
    public SoarPreparedStatement(PreparedStatement ps, String query){
        this.ps = ps;
        this.query = query;
    }
    
    //Use this to make more PreparedStatements
    public String getQuery(){
        return query;
    }
    
    //Use this to see what the Database will see
    private String getConcreteQuery(){
        String toReturn = query;
        int qPos = toReturn.indexOf('?');
        int qIndex = 1;
        while(qPos > -1){
            toReturn = toReturn.replaceFirst(
                    "\\?", 
                    bindVariables.get(qIndex) == null?
                            "Null":
                            bindVariables.get(qIndex).toString()
                );
            qIndex++;
            qPos = toReturn.indexOf('?');
        }
        return toReturn;
    }
    
    @Override
    public void addBatch(String sql) throws SQLException
    {
        ps.addBatch(sql);
    }

    @Override
    public void cancel() throws SQLException
    {
        ps.cancel();
    }

    @Override
    public void clearBatch() throws SQLException
    {
        ps.clearBatch();
    }

    @Override
    public void clearWarnings() throws SQLException
    {
        ps.clearWarnings();
    }

    @Override
    public void close() throws SQLException
    {
        ps.close();
    }

    @Override
    public boolean execute(String sql) throws SQLException
    {
        logger.trace("Executing: " + sql);
        return ps.execute(sql);
    }

    @Override
    public boolean execute(String sql, int autoGeneratedKeys)
            throws SQLException
    {
        logger.trace("Executing: " + sql);
        return ps.execute(sql, autoGeneratedKeys);
    }

    @Override
    public boolean execute(String sql, int[] columnIndexes) throws SQLException
    {
        logger.trace("Executing: " + sql);
        return ps.execute(sql, columnIndexes);
    }

    @Override
    public boolean execute(String sql, String[] columnNames)
            throws SQLException
    {
        logger.trace("Executing: " + sql);
        return ps.execute(sql, columnNames);
    }

    @Override
    public int[] executeBatch() throws SQLException
    {
        return ps.executeBatch();
    }

    @Override
    public ResultSet executeQuery(String sql) throws SQLException
    {
        logger.trace("Executing: " + sql);
        return ps.executeQuery(sql);
    }

    @Override
    public int executeUpdate(String sql) throws SQLException
    {
        logger.trace("Executing: " + sql);
        return ps.executeUpdate(sql);
    }

    @Override
    public int executeUpdate(String sql, int autoGeneratedKeys)
            throws SQLException
    {
        logger.trace("Executing: " + sql);
        return ps.executeUpdate(sql, autoGeneratedKeys);
    }

    @Override
    public int executeUpdate(String sql, int[] columnIndexes)
            throws SQLException
    {
        logger.trace("Executing: " + sql);
        return ps.executeUpdate(sql, columnIndexes);
    }

    @Override
    public int executeUpdate(String sql, String[] columnNames)
            throws SQLException
    {
        logger.trace("Executing: " + sql);
        return ps.executeUpdate(sql, columnNames);
    }

    @Override
    public Connection getConnection() throws SQLException
    {
        return ps.getConnection();
    }

    @Override
    public int getFetchDirection() throws SQLException
    {
        return ps.getFetchDirection();
    }

    @Override
    public int getFetchSize() throws SQLException
    {
        return ps.getFetchSize();
    }

    @Override
    public ResultSet getGeneratedKeys() throws SQLException
    {
        return ps.getGeneratedKeys();
    }

    @Override
    public int getMaxFieldSize() throws SQLException
    {
        return ps.getMaxFieldSize();
    }

    @Override
    public int getMaxRows() throws SQLException
    {
        return ps.getMaxRows();
    }

    @Override
    public boolean getMoreResults() throws SQLException
    {
        return ps.getMoreResults();
    }

    @Override
    public boolean getMoreResults(int current) throws SQLException
    {
        return ps.getMoreResults(current);
    }

    @Override
    public int getQueryTimeout() throws SQLException
    {
        return ps.getQueryTimeout();
    }

    @Override
    public ResultSet getResultSet() throws SQLException
    {
        return ps.getResultSet();
    }

    @Override
    public int getResultSetConcurrency() throws SQLException
    {
        return ps.getResultSetConcurrency();
    }

    @Override
    public int getResultSetHoldability() throws SQLException
    {
        return ps.getResultSetHoldability();
    }

    @Override
    public int getResultSetType() throws SQLException
    {
        return ps.getResultSetType();
    }

    @Override
    public int getUpdateCount() throws SQLException
    {
        return ps.getUpdateCount();
    }

    @Override
    public SQLWarning getWarnings() throws SQLException
    {
        return ps.getWarnings();
    }

    @Override
    public boolean isClosed() throws SQLException
    {
        return ps.isClosed();
    }

    @Override
    public boolean isPoolable() throws SQLException
    {
        return ps.isPoolable();
    }

    @Override
    public void setCursorName(String name) throws SQLException
    {
        ps.setCursorName(name);
    }

    @Override
    public void setEscapeProcessing(boolean enable) throws SQLException
    {
        ps.setEscapeProcessing(enable);
    }

    @Override
    public void setFetchDirection(int direction) throws SQLException
    {
        ps.setFetchDirection(direction);
    }

    @Override
    public void setFetchSize(int rows) throws SQLException
    {
        ps.setFetchSize(rows);
    }

    @Override
    public void setMaxFieldSize(int max) throws SQLException
    {
        ps.setMaxFieldSize(max);
    }

    @Override
    public void setMaxRows(int max) throws SQLException
    {
        ps.setMaxRows(max);
    }

    @Override
    public void setPoolable(boolean poolable) throws SQLException
    {
        ps.setPoolable(poolable);
    }

    @Override
    public void setQueryTimeout(int seconds) throws SQLException
    {
        ps.setQueryTimeout(seconds);
    }

    @Override
    public boolean isWrapperFor(Class<?> iface) throws SQLException
    {
        return ps.isWrapperFor(iface);
    }

    @Override
    public <T> T unwrap(Class<T> iface) throws SQLException
    {
        return ps.unwrap(iface);
    }

    @Override
    public void addBatch() throws SQLException
    {
        ps.addBatch();
    }

    @Override
    public void clearParameters() throws SQLException
    {
        bindVariables.clear();
        ps.clearParameters();
    }

    @Override
    public boolean execute() throws SQLException
    {
        logger.trace("Executing: " + getConcreteQuery());
        return ps.execute();
    }

    @Override
    public ResultSet executeQuery() throws SQLException
    {
        logger.trace("Executing: " + getConcreteQuery());
        return ps.executeQuery();
    }

    @Override
    public int executeUpdate() throws SQLException
    {
        logger.trace("Executing: " + getConcreteQuery());
        return ps.executeUpdate();
    }

    @Override
    public ResultSetMetaData getMetaData() throws SQLException
    {
        return ps.getMetaData();
    }

    @Override
    public ParameterMetaData getParameterMetaData() throws SQLException
    {
        return ps.getParameterMetaData();
    }

    @Override
    public void setArray(int parameterIndex, Array x) throws SQLException
    {
        bindVariables.put(parameterIndex, x);
        ps.setArray(parameterIndex, x);
    }

    @Override
    public void setAsciiStream(int parameterIndex, InputStream x)
            throws SQLException
    {
        bindVariables.put(parameterIndex, x);
        ps.setAsciiStream(parameterIndex, x);
    }

    @Override
    public void setAsciiStream(int parameterIndex, InputStream x, int length)
            throws SQLException
    {
        bindVariables.put(parameterIndex, x);
        ps.setAsciiStream(parameterIndex, x, length);
    }

    @Override
    public void setAsciiStream(int parameterIndex, InputStream x, long length)
            throws SQLException
    {
        bindVariables.put(parameterIndex, x);
        ps.setAsciiStream(parameterIndex, x, length);
    }

    @Override
    public void setBigDecimal(int parameterIndex, BigDecimal x)
            throws SQLException
    {
        bindVariables.put(parameterIndex, x);
        ps.setBigDecimal(parameterIndex, x);
    }

    @Override
    public void setBinaryStream(int parameterIndex, InputStream x)
            throws SQLException
    {
        bindVariables.put(parameterIndex, x);
        ps.setBinaryStream(parameterIndex, x);
    }

    @Override
    public void setBinaryStream(int parameterIndex, InputStream x, int length)
            throws SQLException
    {
        bindVariables.put(parameterIndex, x);
        ps.setBinaryStream(parameterIndex, x, length);
    }

    @Override
    public void setBinaryStream(int parameterIndex, InputStream x, long length)
            throws SQLException
    {
        bindVariables.put(parameterIndex, x);
        ps.setBinaryStream(parameterIndex, x, length);
    }

    @Override
    public void setBlob(int parameterIndex, Blob x) throws SQLException
    {
        bindVariables.put(parameterIndex, x);
        ps.setBlob(parameterIndex, x);
    }

    @Override
    public void setBlob(int parameterIndex, InputStream inputStream)
            throws SQLException
    {
        bindVariables.put(parameterIndex, inputStream);
        ps.setBlob(parameterIndex, inputStream);
    }

    @Override
    public void setBlob(int parameterIndex, InputStream inputStream, long length)
            throws SQLException
    {
        bindVariables.put(parameterIndex, inputStream);
        ps.setBlob(parameterIndex, inputStream, length);
    }

    @Override
    public void setBoolean(int parameterIndex, boolean x) throws SQLException
    {
        bindVariables.put(parameterIndex, x);
        ps.setBoolean(parameterIndex, x);
    }

    @Override
    public void setByte(int parameterIndex, byte x) throws SQLException
    {
        bindVariables.put(parameterIndex, x);
        ps.setByte(parameterIndex, x);
    }

    @Override
    public void setBytes(int parameterIndex, byte[] x) throws SQLException
    {
        bindVariables.put(parameterIndex, x);
        ps.setBytes(parameterIndex, x);
    }

    @Override
    public void setCharacterStream(int parameterIndex, Reader reader)
            throws SQLException
    {
        bindVariables.put(parameterIndex, reader);
        ps.setCharacterStream(parameterIndex, reader);
    }

    @Override
    public void setCharacterStream(int parameterIndex, Reader reader, int length)
            throws SQLException
    {
        bindVariables.put(parameterIndex, reader);
        ps.setCharacterStream(parameterIndex, reader, length);
    }

    @Override
    public void setCharacterStream(int parameterIndex, Reader reader,
            long length) throws SQLException
    {
        bindVariables.put(parameterIndex, reader);
        ps.setCharacterStream(parameterIndex, reader, length);
    }

    @Override
    public void setClob(int parameterIndex, Clob x) throws SQLException
    {
        bindVariables.put(parameterIndex, x);
        ps.setClob(parameterIndex, x);
    }

    @Override
    public void setClob(int parameterIndex, Reader reader) throws SQLException
    {
        bindVariables.put(parameterIndex, reader);
        ps.setClob(parameterIndex, reader);
    }

    @Override
    public void setClob(int parameterIndex, Reader reader, long length)
            throws SQLException
    {
        bindVariables.put(parameterIndex, reader);
        ps.setClob(parameterIndex, reader, length);
    }

    @Override
    public void setDate(int parameterIndex, Date x) throws SQLException
    {
        bindVariables.put(parameterIndex, x);
        ps.setDate(parameterIndex, x);
    }

    @Override
    public void setDate(int parameterIndex, Date x, Calendar cal)
            throws SQLException
    {
        bindVariables.put(parameterIndex, x);
        ps.setDate(parameterIndex, x, cal);
    }

    @Override
    public void setDouble(int parameterIndex, double x) throws SQLException
    {
        bindVariables.put(parameterIndex, x);
        ps.setDouble(parameterIndex, x);
    }

    @Override
    public void setFloat(int parameterIndex, float x) throws SQLException
    {
        bindVariables.put(parameterIndex, x);
        ps.setFloat(parameterIndex, x);
    }

    @Override
    public void setInt(int parameterIndex, int x) throws SQLException
    {
        bindVariables.put(parameterIndex, x);
        ps.setInt(parameterIndex, x);
    }

    @Override
    public void setLong(int parameterIndex, long x) throws SQLException
    {
        bindVariables.put(parameterIndex, x);
        ps.setLong(parameterIndex, x);
    }

    @Override
    public void setNCharacterStream(int parameterIndex, Reader value)
            throws SQLException
    {
        bindVariables.put(parameterIndex, value);
        ps.setNCharacterStream(parameterIndex, value);
    }

    @Override
    public void setNCharacterStream(int parameterIndex, Reader value,
            long length) throws SQLException
    {
        bindVariables.put(parameterIndex, value);
        ps.setCharacterStream(parameterIndex, value, length);
    }

    @Override
    public void setNClob(int parameterIndex, NClob value) throws SQLException
    {
        bindVariables.put(parameterIndex, value);
        ps.setNClob(parameterIndex, value);
    }

    @Override
    public void setNClob(int parameterIndex, Reader reader) throws SQLException
    {
        bindVariables.put(parameterIndex, reader);
        ps.setNClob(parameterIndex, reader);
    }

    @Override
    public void setNClob(int parameterIndex, Reader reader, long length)
            throws SQLException
    {
        bindVariables.put(parameterIndex, reader);
        ps.setNClob(parameterIndex, reader, length);
    }

    @Override
    public void setNString(int parameterIndex, String value)
            throws SQLException
    {
        bindVariables.put(parameterIndex, value);
        ps.setNString(parameterIndex, value);
    }

    @Override
    public void setNull(int parameterIndex, int sqlType) throws SQLException
    {
        bindVariables.put(parameterIndex, null);
        ps.setNull(parameterIndex, sqlType);
    }

    @Override
    public void setNull(int parameterIndex, int sqlType, String typeName)
            throws SQLException
    {
        bindVariables.put(parameterIndex, null);
        ps.setNull(parameterIndex, sqlType, typeName);
    }

    @Override
    public void setObject(int parameterIndex, Object x) throws SQLException
    {
        bindVariables.put(parameterIndex, x);
        ps.setObject(parameterIndex, x);
    }

    @Override
    public void setObject(int parameterIndex, Object x, int targetSqlType)
            throws SQLException
    {
        bindVariables.put(parameterIndex, x);
        ps.setObject(parameterIndex, x, targetSqlType);
    }

    @Override
    public void setObject(int parameterIndex, Object x, int targetSqlType,
            int scaleOrLength) throws SQLException
    {
        bindVariables.put(parameterIndex, x);
        ps.setObject(parameterIndex, x, targetSqlType, scaleOrLength);
    }

    @Override
    public void setRef(int parameterIndex, Ref x) throws SQLException
    {
        bindVariables.put(parameterIndex, x);
        ps.setRef(parameterIndex, x);
    }

    @Override
    public void setRowId(int parameterIndex, RowId x) throws SQLException
    {
        bindVariables.put(parameterIndex, x);
        ps.setRowId(parameterIndex, x);
    }

    @Override
    public void setSQLXML(int parameterIndex, SQLXML xmlObject)
            throws SQLException
    {
        bindVariables.put(parameterIndex, xmlObject);
        ps.setSQLXML(parameterIndex, xmlObject);
    }

    @Override
    public void setShort(int parameterIndex, short x) throws SQLException
    {
        bindVariables.put(parameterIndex, x);
        ps.setShort(parameterIndex, x);
    }

    @Override
    public void setString(int parameterIndex, String x) throws SQLException
    {
        bindVariables.put(parameterIndex, x);
        ps.setString(parameterIndex, x);
    }

    @Override
    public void setTime(int parameterIndex, Time x) throws SQLException
    {
        bindVariables.put(parameterIndex, x);
        ps.setTime(parameterIndex, x);
    }

    @Override
    public void setTime(int parameterIndex, Time x, Calendar cal)
            throws SQLException
    {
        bindVariables.put(parameterIndex, x);
        ps.setTime(parameterIndex, x, cal);
    }

    @Override
    public void setTimestamp(int parameterIndex, Timestamp x)
            throws SQLException
    {
        bindVariables.put(parameterIndex, x);
        ps.setTimestamp(parameterIndex, x);
    }

    @Override
    public void setTimestamp(int parameterIndex, Timestamp x, Calendar cal)
            throws SQLException
    {
        bindVariables.put(parameterIndex, x);
        ps.setTimestamp(parameterIndex, x, cal);
    }

    @Override
    public void setURL(int parameterIndex, URL x) throws SQLException
    {
        bindVariables.put(parameterIndex, x);
        ps.setURL(parameterIndex, x);
    }

    @Override
    public void setUnicodeStream(int parameterIndex, InputStream x, int length)
            throws SQLException
    {
        bindVariables.put(parameterIndex, x);
        ps.setUnicodeStream(parameterIndex, x, length);
    }

}
