/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.35
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package sml;

public class FloatElement extends WMElement {

    private double value;
    private String stringForm;

    FloatElement(Agent agent, IdentifierSymbol parentSymbol, String pid, String attributeName, double value, int timeTag)
    {
        super(agent, parentSymbol, pid, attributeName, timeTag);
        this.value = value;
        this.stringForm = Double.toString(value);
    }
    FloatElement(Agent agent, Identifier parent, String pid, String attributeName, double value, int timeTag)
    {
        super(agent, parent.GetSymbol(), pid, attributeName, timeTag);
        this.value = value;
        this.stringForm = Double.toString(value);
    }

public synchronized void delete() {
    super.delete();
  }

  public String GetValueType() {
      return sml_Names.getKTypeDouble();
  }

  public String GetValueAsString() {
      return stringForm;
  }

  public double GetValue() {
      return value;
  }

  public FloatElement ConvertToFloatElement() {
      return this;
  }
  
  void SetValue(double value)
  {
      this.value = value ;
  }

}
