/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.35
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package sml;

public class IntElement extends WMElement {

    private int value;
    private String stringForm;
    IntElement(Agent agent, IdentifierSymbol parentSymbol, String pid, String attributeName, int value, int timeTag)
    {
        super(agent, parentSymbol, pid, attributeName, timeTag);
        this.value = value;
        this.stringForm = Integer.toString(value);
    }
    
    IntElement(Agent agent, Identifier parent, String pid, String attributeName, int value, int timeTag)
    {
        super(agent, parent.GetSymbol(), pid, attributeName, timeTag);
        this.value = value;
        this.stringForm = Integer.toString(value);
    }

public synchronized void delete() {
    super.delete();
  }

  public String GetValueType() {
      return sml_Names.getKTypeInt();
  }

  public String GetValueAsString() {
      return stringForm;
  }

  public int GetValue() {
      return value;
  }

  public IntElement ConvertToIntElement() {
      return this;
  }
  
  void SetValue(int value)
  {
      this.value = value ;
  }

}
