/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.35
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package sml;

public enum smlPhase {
  sml_INPUT_PHASE,
  sml_PROPOSAL_PHASE,
  sml_DECISION_PHASE,
  sml_APPLY_PHASE,
  sml_OUTPUT_PHASE;

  public final int swigValue() {
    return swigValue;
  }

  public static smlPhase swigToEnum(int swigValue) {
    smlPhase[] swigValues = smlPhase.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (smlPhase swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + smlPhase.class + " with value " + swigValue);
  }

  private smlPhase() {
    this.swigValue = SwigNext.next++;
  }

  private smlPhase(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  private smlPhase(smlPhase swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

