/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.35
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package sml;

import java.util.Collection;

import org.jsoar.kernel.memory.Wme;

public class WMElement {
    // The agent which owns this WME.
    Agent  m_Agent ;
    Wme wme;
    
    // The id for this wme (can be NULL if we're at the top of the tree)
    IdentifierSymbol   m_ID ;

    // This is true if the wme was just added.  The client chooses when to clear these flags.
    boolean    m_JustAdded ;

    public static <T extends WMElement> T findByTimeTag(Collection<T> wmes, int timetag)
    {
        for(T w : wmes)
        {
            if(timetag == w.GetTimeTag())
            {
                return w;
            }
        }
        return null;
    }
  public synchronized void delete() {
  }

  public boolean IsJustAdded() {
      return m_JustAdded;
  }

  public IdentifierSymbol GetParent() {
      return m_ID;
  }

  public IdentifierSymbol GetIdentifier() {
      return m_ID;
  }

  public String GetIdentifierName() {
      return wme != null ? wme.getIdentifier().toString() : "";
  }

  public String GetAttribute() {
      return wme.getAttribute().toString();
  }

  public String GetValueType() { throw new UnsupportedOperationException(""); }

  public String GetValueAsString() { return wme.getValue().toString(); }

  public int GetTimeTag() {
      return wme.getTimetag();
  }

  public boolean IsIdentifier() {
      return false;
  }

  public Identifier ConvertToIdentifier() {
      return null;
  }

  public IntElement ConvertToIntElement() {
      return null;
  }

  public FloatElement ConvertToFloatElement() {
      return null;
  }

  public StringElement ConvertToStringElement() {
      return null;
  }

  public Agent GetAgent() {
      return m_Agent;
  }

  // the methods exposed in the agent class.  This makes it clear that the
  // agent owns all objects.
  WMElement(Agent pAgent, IdentifierSymbol pParentSymbol, Wme wme)
  {
      this.m_Agent = pAgent;
      this.m_ID = pParentSymbol;
      this.wme = wme;
  }
  // virtual ~WMElement(void);

  void    SetJustAdded(boolean state) { m_JustAdded = state ; }

  void SetParent(Identifier pParent)
  {
      m_ID = pParent.GetSymbol();
  }

  // Send over to the kernel again
  void Refresh()
  {
      //GetAgent().GetWM().GetInputDeltaList().AddWME(this) ;      
  }

}
