/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.35
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package sml;

import sml.connection.Connection;

public class Agent extends ClientErrors {
  private long swigCPtr;

  protected Agent(long cPtr, boolean cMemoryOwn) {
    super(smlJNI.SWIGAgentUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Agent obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public synchronized void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      throw new UnsupportedOperationException("C++ destructor does not have public access");
    }
    swigCPtr = 0;
    super.delete();
  }

  public interface RunEventInterface {
	public void runEventHandler(int eventID, Object data, Agent agent, int phase) ;
  }

  public interface ProductionEventInterface {
     public void productionEventHandler(int eventID, Object data, Agent agent, String prodName, String instantiation) ;
  }
  
  public interface PrintEventInterface { 
  		public void printEventHandler(int eventID, Object data, Agent agent, String message) ;
  }
  
  public interface xmlEventInterface {
  		public void xmlEventHandler(int eventID, Object data, Agent agent, ClientXML xml) ;
  }

  public interface OutputEventInterface {  
  		public void outputEventHandler(Object data, String agentName, String attributeName, WMElement pWmeAdded) ;
  }
  
  public interface OutputNotificationInterface {
  		public void outputNotificationHandler(Object data, Agent agent) ;
  }

  public int RegisterForRunEvent(smlRunEventId id, RunEventInterface handlerObject, Object callbackData)
  { return smlJNI.Agent_RegisterForRunEvent(swigCPtr, id.swigValue(), this, handlerObject, callbackData) ;}
  
  public int RegisterForProductionEvent(smlProductionEventId id, ProductionEventInterface handlerObject, Object callbackData)
  { return smlJNI.Agent_RegisterForProductionEvent(swigCPtr, id.swigValue(), this, handlerObject, callbackData) ; }

  public int RegisterForPrintEvent(smlPrintEventId id, PrintEventInterface handlerObject, Object callbackData)
  { return smlJNI.Agent_RegisterForPrintEvent(swigCPtr, id.swigValue(), this, handlerObject, callbackData, true) ; }

  public int RegisterForPrintEvent(smlPrintEventId id, PrintEventInterface handlerObject, Object callbackData, boolean ignoreOwnEchos)
  { return smlJNI.Agent_RegisterForPrintEvent(swigCPtr, id.swigValue(), this, handlerObject, callbackData, ignoreOwnEchos) ; }

  public int RegisterForXMLEvent(smlXMLEventId id, xmlEventInterface handlerObject, Object callbackData)
  { return smlJNI.Agent_RegisterForXMLEvent(swigCPtr, id.swigValue(), this, handlerObject, callbackData) ; }
  
  public int RegisterForOutputNotification(OutputNotificationInterface handlerObject, Object callbackData)
  { return smlJNI.Agent_RegisterForOutputNotification(swigCPtr, this, handlerObject, callbackData) ;}

  public boolean UnregisterForOutputNotification(int callbackReturnValue)
  { return smlJNI.Agent_UnregisterForOutputNotification(swigCPtr, callbackReturnValue) ;}

  public boolean UnregisterForRunEvent(int callbackReturnValue)
  { return smlJNI.Agent_UnregisterForRunEvent(swigCPtr, callbackReturnValue) ;}

  public boolean UnregisterForProductionEvent(int callbackReturnValue)
  { return smlJNI.Agent_UnregisterForProductionEvent(swigCPtr, callbackReturnValue) ;}

  public boolean UnregisterForPrintEvent(int callbackReturnValue)
  { return smlJNI.Agent_UnregisterForPrintEvent(swigCPtr, callbackReturnValue) ;}

  public boolean UnregisterForXMLEvent(int callbackReturnValue)
  { return smlJNI.Agent_UnregisterForXMLEvent(swigCPtr, callbackReturnValue) ;}

  public int AddOutputHandler(String attributeName, OutputEventInterface handlerObject, Object callbackData)
  { return smlJNI.Agent_AddOutputHandler(swigCPtr, attributeName, this, handlerObject, callbackData) ; }

  public boolean RemoveOutputHandler(int callbackReturnValue)
  { return smlJNI.Agent_RemoveOutputHandler(swigCPtr, callbackReturnValue) ;}

  public String GetAgentName() {
    return smlJNI.Agent_GetAgentName(swigCPtr, this);
  }

  public Kernel GetKernel() {
    long cPtr = smlJNI.Agent_GetKernel(swigCPtr, this);
    return (cPtr == 0) ? null : new Kernel(cPtr, false);
  }

  public int GenerateNewVisitedCounter() {
    return smlJNI.Agent_GenerateNewVisitedCounter(swigCPtr, this);
  }

  public boolean LoadProductions(String pFilename, boolean echoResults) {
    return smlJNI.Agent_LoadProductions__SWIG_0(swigCPtr, this, pFilename, echoResults);
  }

  public boolean LoadProductions(String pFilename) {
    return smlJNI.Agent_LoadProductions__SWIG_1(swigCPtr, this, pFilename);
  }

  public Identifier GetInputLink() {
      throw new UnsupportedOperationException("Not implemented");
  }

  public Identifier GetILink() {
      throw new UnsupportedOperationException("Not implemented");
  }

  public Identifier GetOutputLink() {
      throw new UnsupportedOperationException("Not implemented");
  }

  public StringElement CreateStringWME(Identifier parent, String pAttribute, String pValue) {
      throw new UnsupportedOperationException("Not implemented");
  }

  public IntElement CreateIntWME(Identifier parent, String pAttribute, int value) {
      throw new UnsupportedOperationException("Not implemented");
  }

  public FloatElement CreateFloatWME(Identifier parent, String pAttribute, double value) {
      throw new UnsupportedOperationException("Not implemented");
  }

  public Identifier CreateIdWME(Identifier parent, String pAttribute) {
      throw new UnsupportedOperationException("Not implemented");
  }

  public Identifier CreateSharedIdWME(Identifier parent, String pAttribute, Identifier pSharedValue) {
      throw new UnsupportedOperationException("Not implemented");
  }

  public void Update(StringElement pWME, String pValue) {
      throw new UnsupportedOperationException("Not implemented");
  }

  public void Update(IntElement pWME, int value) {
      throw new UnsupportedOperationException("Not implemented");
  }

  public void Update(FloatElement pWME, double value) {
      throw new UnsupportedOperationException("Not implemented");
  }

  public void SetBlinkIfNoChange(boolean state) {
    smlJNI.Agent_SetBlinkIfNoChange(swigCPtr, this, state);
  }

  public boolean IsBlinkIfNoChange() {
    return smlJNI.Agent_IsBlinkIfNoChange(swigCPtr, this);
  }

  public boolean DestroyWME(WMElement pWME) {
      throw new UnsupportedOperationException("Not implemented");
  }

  public String InitSoar() {
    return smlJNI.Agent_InitSoar(swigCPtr, this);
  }

  public int GetNumberOutputLinkChanges() {
    return smlJNI.Agent_GetNumberOutputLinkChanges(swigCPtr, this);
  }

  public WMElement GetOutputLinkChange(int index) {
      throw new UnsupportedOperationException("Not implemented");
  }

  public boolean IsOutputLinkChangeAdd(int index) {
    return smlJNI.Agent_IsOutputLinkChangeAdd(swigCPtr, this, index);
  }

  public void ClearOutputLinkChanges() {
    smlJNI.Agent_ClearOutputLinkChanges(swigCPtr, this);
  }

  public int GetNumberCommands() {
    return smlJNI.Agent_GetNumberCommands(swigCPtr, this);
  }

  public boolean Commands() {
    return smlJNI.Agent_Commands(swigCPtr, this);
  }

  public Identifier GetCommand(int index) {
      throw new UnsupportedOperationException("Not implemented");
  }

  public boolean Commit() {
    return smlJNI.Agent_Commit(swigCPtr, this);
  }

  public boolean IsCommitRequired() {
    return smlJNI.Agent_IsCommitRequired(swigCPtr, this);
  }

  public String RunSelf(long numberSteps, smlRunStepSize stepSize) {
    return smlJNI.Agent_RunSelf__SWIG_0(swigCPtr, this, numberSteps, stepSize.swigValue());
  }

  public String RunSelf(long numberSteps) {
    return smlJNI.Agent_RunSelf__SWIG_1(swigCPtr, this, numberSteps);
  }

  public String RunSelfForever() {
    return smlJNI.Agent_RunSelfForever(swigCPtr, this);
  }

  public String RunSelfTilOutput() {
    return smlJNI.Agent_RunSelfTilOutput(swigCPtr, this);
  }

  public boolean WasAgentOnRunList() {
    return smlJNI.Agent_WasAgentOnRunList(swigCPtr, this);
  }

  public smlRunResult GetResultOfLastRun() {
    return smlRunResult.swigToEnum(smlJNI.Agent_GetResultOfLastRun(swigCPtr, this));
  }

  public String StopSelf() {
    return smlJNI.Agent_StopSelf(swigCPtr, this);
  }

  public void Refresh() {
    smlJNI.Agent_Refresh(swigCPtr, this);
  }

  public smlPhase GetCurrentPhase() {
    return smlPhase.swigToEnum(smlJNI.Agent_GetCurrentPhase(swigCPtr, this));
  }

  public int GetDecisionCycleCounter() {
    return smlJNI.Agent_GetDecisionCycleCounter(swigCPtr, this);
  }

  public smlRunState GetRunState() {
    return smlRunState.swigToEnum(smlJNI.Agent_GetRunState(swigCPtr, this));
  }

  public String ExecuteCommandLine(String pCommandLine, boolean echoResults, boolean noFilter) {
    return smlJNI.Agent_ExecuteCommandLine__SWIG_0(swigCPtr, this, pCommandLine, echoResults, noFilter);
  }

  public String ExecuteCommandLine(String pCommandLine, boolean echoResults) {
    return smlJNI.Agent_ExecuteCommandLine__SWIG_1(swigCPtr, this, pCommandLine, echoResults);
  }

  public String ExecuteCommandLine(String pCommandLine) {
    return smlJNI.Agent_ExecuteCommandLine__SWIG_2(swigCPtr, this, pCommandLine);
  }

  public boolean ExecuteCommandLineXML(String pCommandLine, ClientAnalyzedXML pResponse) {
      throw new UnsupportedOperationException("Not implemented");
  }

  public boolean GetLastCommandLineResult() {
    return smlJNI.Agent_GetLastCommandLineResult(swigCPtr, this);
  }

  public boolean IsProductionLoaded(String pProductionName) {
    return smlJNI.Agent_IsProductionLoaded(swigCPtr, this, pProductionName);
  }

  public boolean SynchronizeInputLink() {
    return smlJNI.Agent_SynchronizeInputLink(swigCPtr, this);
  }

  public boolean SynchronizeOutputLink() {
    return smlJNI.Agent_SynchronizeOutputLink(swigCPtr, this);
  }

    /**
     * @return
     */
    WorkingMemory GetWM()
    {
        throw new UnsupportedOperationException("Not implemented");
    }

    /**
     * 
     */
    void FireOutputNotification()
    {
        throw new UnsupportedOperationException("Not implemented");
    }

    /**
     * @return
     */
    boolean IsRegisteredForOutputEvent()
    {
        throw new UnsupportedOperationException("Not implemented");
    }

    /**
     * @param wme
     */
    void ReceivedOutputEvent(WMElement wme)
    {
        throw new UnsupportedOperationException("Not implemented");
    }

    /**
     * @return
     */
    Connection GetConnection()
    {
        // TODO Auto-generated method stub
        return null;
    }

    /**
     * @return
     */
    boolean IsAutoCommitEnabled()
    {
        // TODO Auto-generated method stub
        return false;
    }

}
