/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.35
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package sml;

public class AnalyzeXML {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected AnalyzeXML(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(AnalyzeXML obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      smlJNI.delete_AnalyzeXML(swigCPtr);
    }
    swigCPtr = 0;
  }

  public AnalyzeXML() {
    this(smlJNI.new_AnalyzeXML(), true);
  }

  public void Analyze(ElementXML pRootXML) {
    smlJNI.AnalyzeXML_Analyze(swigCPtr, this, ElementXML.getCPtr(pRootXML), pRootXML);
  }

  public SWIGTYPE_p_ElementXML_InterfaceStruct GetElementXMLHandle() {
    long cPtr = smlJNI.AnalyzeXML_GetElementXMLHandle(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_ElementXML_InterfaceStruct(cPtr, false);
  }

  public ElementXML GetCommandTag() {
    long cPtr = smlJNI.AnalyzeXML_GetCommandTag(swigCPtr, this);
    return (cPtr == 0) ? null : new ElementXML(cPtr, false);
  }

  public ElementXML GetResultTag() {
    long cPtr = smlJNI.AnalyzeXML_GetResultTag(swigCPtr, this);
    return (cPtr == 0) ? null : new ElementXML(cPtr, false);
  }

  public ElementXML GetErrorTag() {
    long cPtr = smlJNI.AnalyzeXML_GetErrorTag(swigCPtr, this);
    return (cPtr == 0) ? null : new ElementXML(cPtr, false);
  }

  public boolean IsSML() {
    return smlJNI.AnalyzeXML_IsSML(swigCPtr, this);
  }

  public String GetCommandName() {
    return smlJNI.AnalyzeXML_GetCommandName(swigCPtr, this);
  }

  public String GetResultString() {
    return smlJNI.AnalyzeXML_GetResultString(swigCPtr, this);
  }

  public int GetResultInt(int defaultValue) {
    return smlJNI.AnalyzeXML_GetResultInt(swigCPtr, this, defaultValue);
  }

  public boolean GetResultBool(boolean defaultValue) {
    return smlJNI.AnalyzeXML_GetResultBool(swigCPtr, this, defaultValue);
  }

  public double GetResultFloat(double defaultValue) {
    return smlJNI.AnalyzeXML_GetResultFloat(swigCPtr, this, defaultValue);
  }

  public String GenerateXMLString(boolean includeChildren, boolean insertNewLines) {
    return smlJNI.AnalyzeXML_GenerateXMLString__SWIG_0(swigCPtr, this, includeChildren, insertNewLines);
  }

  public String GenerateXMLString(boolean includeChildren) {
    return smlJNI.AnalyzeXML_GenerateXMLString__SWIG_1(swigCPtr, this, includeChildren);
  }

  public static void DeleteString(String pString) {
    smlJNI.AnalyzeXML_DeleteString(pString);
  }

  public String GetArgString(String pArgName) {
    return smlJNI.AnalyzeXML_GetArgString(swigCPtr, this, pArgName);
  }

  public boolean GetArgBool(String pArgName, boolean defaultValue) {
    return smlJNI.AnalyzeXML_GetArgBool(swigCPtr, this, pArgName, defaultValue);
  }

  public int GetArgInt(String pArgName, int defaultValue) {
    return smlJNI.AnalyzeXML_GetArgInt(swigCPtr, this, pArgName, defaultValue);
  }

  public double GetArgFloat(String pArgName, double defaultValue) {
    return smlJNI.AnalyzeXML_GetArgFloat(swigCPtr, this, pArgName, defaultValue);
  }

}
