/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.35
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package sml;

public class ClientXML {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected ClientXML(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ClientXML obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      smlJNI.delete_ClientXML(swigCPtr);
    }
    swigCPtr = 0;
  }

  public ClientXML() {
    this(smlJNI.new_ClientXML__SWIG_1(), true);
  }

  public ClientXML(ClientXML pXML) {
    this(smlJNI.new_ClientXML__SWIG_2(ClientXML.getCPtr(pXML), pXML), true);
  }

  public ClientTraceXML ConvertToTraceXML() {
    long cPtr = smlJNI.ClientXML_ConvertToTraceXML(swigCPtr, this);
    return (cPtr == 0) ? null : new ClientTraceXML(cPtr, false);
  }

  public String GetTagName() {
    return smlJNI.ClientXML_GetTagName(swigCPtr, this);
  }

  public boolean IsTag(String pTagName) {
    return smlJNI.ClientXML_IsTag(swigCPtr, this, pTagName);
  }

  public int GetNumberChildren() {
    return smlJNI.ClientXML_GetNumberChildren(swigCPtr, this);
  }

  public boolean GetChild(ClientXML pChild, int index) {
    return smlJNI.ClientXML_GetChild(swigCPtr, this, ClientXML.getCPtr(pChild), pChild, index);
  }

  public int GetNumberAttributes() {
    return smlJNI.ClientXML_GetNumberAttributes(swigCPtr, this);
  }

  public String GetAttributeName(int index) {
    return smlJNI.ClientXML_GetAttributeName(swigCPtr, this, index);
  }

  public String GetAttributeValue(int index) {
    return smlJNI.ClientXML_GetAttributeValue(swigCPtr, this, index);
  }

  public String GetAttribute(String attName) {
    return smlJNI.ClientXML_GetAttribute(swigCPtr, this, attName);
  }

  public String GetCharacterData() {
    return smlJNI.ClientXML_GetCharacterData(swigCPtr, this);
  }

  public boolean IsCharacterDataBinary() {
    return smlJNI.ClientXML_IsCharacterDataBinary(swigCPtr, this);
  }

  public boolean ConvertCharacterDataToBinary() {
    return smlJNI.ClientXML_ConvertCharacterDataToBinary(swigCPtr, this);
  }

  public int GetCharacterDataLength() {
    return smlJNI.ClientXML_GetCharacterDataLength(swigCPtr, this);
  }

  public String GenerateXMLString(boolean includeChildren, boolean insertNewLines) {
    return smlJNI.ClientXML_GenerateXMLString__SWIG_0(swigCPtr, this, includeChildren, insertNewLines);
  }

  public String GenerateXMLString(boolean includeChildren) {
    return smlJNI.ClientXML_GenerateXMLString__SWIG_1(swigCPtr, this, includeChildren);
  }

  public int DetermineXMLStringLength(boolean includeChildren, boolean insertNewLines) {
    return smlJNI.ClientXML_DetermineXMLStringLength__SWIG_0(swigCPtr, this, includeChildren, insertNewLines);
  }

  public int DetermineXMLStringLength(boolean includeChildren) {
    return smlJNI.ClientXML_DetermineXMLStringLength__SWIG_1(swigCPtr, this, includeChildren);
  }

  public static String AllocateString(int length) {
    return smlJNI.ClientXML_AllocateString(length);
  }

  public static void DeleteString(String pString) {
    smlJNI.ClientXML_DeleteString(pString);
  }

  public static String CopyString(String original) {
    return smlJNI.ClientXML_CopyString(original);
  }

  public static String CopyBuffer(String original, int length) {
    return smlJNI.ClientXML_CopyBuffer(original, length);
  }

}
