/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.35
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package sml;

public class ClientTraceXML extends ClientXML {

  public synchronized void delete() {
    super.delete();
  }

  public boolean IsTagTrace() {
      return IsTag(sml_Names.getKTagTrace());
  }

  public boolean IsTagRhsWrite() {
      return IsTag(sml_Names.getKTagRHS_write());
  }

  public String GetString() {
      return GetAttribute(sml_Names.getKRHS_String());
  }

  public boolean IsTagState() {
      return IsTag(sml_Names.getKTagState());
  }

  public String GetDecisionCycleCount() {
      return GetAttribute(sml_Names.getKState_DecisionCycleCt());
  }

  public String GetStateID() {
      return GetAttribute(sml_Names.getKState_ID());
  }

  public String GetImpasseObject() {
      return GetAttribute(sml_Names.getKState_ImpasseObject());
  }

  public String GetImpasseType() {
      return GetAttribute(sml_Names.getKState_ImpasseType());
  }

  public String GetStackLevel() {
      return GetAttribute(sml_Names.getKState_StackLevel());
  }

  public boolean IsTagOperator() {
      return IsTag(sml_Names.getKTagOperator());
  }

  public String GetOperatorID() {
      return GetAttribute(sml_Names.getKOperator_ID());
  }

  public String GetOperatorName() {
      return GetAttribute(sml_Names.getKOperator_Name());
  }

  public boolean IsTagPhase() {
      return IsTag(sml_Names.getKTagPhase());
  }

  public String GetPhaseName() {
      return GetAttribute(sml_Names.getKPhase_Name());
  }

  public String GetPhaseStatus() {
      return GetAttribute(sml_Names.getKPhase_Status());
  }

  public String GetFiringType() {
      return GetAttribute(sml_Names.getKPhase_FiringType());
  }

  public String GetLevelNum() {
      return GetAttribute(sml_Names.getKPhase_LevelNum());
  }

  public boolean IsTagSubphase() {
      return IsTag(sml_Names.getKTagSubphase());
  }

  public boolean IsSubphaseNameFiringProductions() {
      String phase = GetPhaseName();
      return phase != null && phase.equals(sml_Names.getKSubphaseName_FiringProductions());
  }

  public boolean IsSubphaseNameChangingWorkingMemory() {
      String phase = GetPhaseName();
      return phase != null && phase.equals(sml_Names.getKSubphaseName_ChangingWorkingMemory());
  }

  public boolean IsTagFiringProduction() {
      return IsTag(sml_Names.getKTagProduction_Firing());
  }

  public boolean IsTagRetractingProduction() {
      return IsTag(sml_Names.getKTagProduction_Retracting());
  }

  public boolean IsTagLearning() {
      return IsTag(sml_Names.getKTagLearning());
  }

  public boolean IsTagProduction() {
      return IsTag(sml_Names.getKTagProduction());
  }

  public String GetProductionName() {
      return GetAttribute(sml_Names.getKProduction_Name());
  }

  public String GetProductionDoc() {
      return GetAttribute(sml_Names.getKProductionDocumentation());
  }

  public String GetProductionType() {
      return GetAttribute(sml_Names.getKProductionType());
  }

  public String GetProductionDeclaredSupport() {
      return GetAttribute(sml_Names.getKProductionDeclaredISupport());
  }

  public boolean IsTagConditions() {
      return IsTag(sml_Names.getKTagConditions());
  }

  public boolean IsTagCondition() {
      return IsTag(sml_Names.getKTagCondition());
  }

  public boolean IsTagConjunctiveNegationCondition() {
      return IsTag(sml_Names.getKTagConjunctive_Negation_Condition());
  }

  public boolean IsTagActions() {
      return IsTag(sml_Names.getKTagActions());
  }

  public boolean IsTagAction() {
      return IsTag(sml_Names.getKTagAction());
  }

  public String GetConditionTest() {
      return GetAttribute(sml_Names.getKConditionTest());
  }

  public String GetConditionId() {
      return GetAttribute(sml_Names.getKConditionId());
  }

  public String GetCondition() {
      return GetAttribute(sml_Names.getKCondition());
  }

  public String GetActionId() {
      return GetAttribute(sml_Names.getKActionId());
  }

  public String GetAction() {
      return GetAttribute(sml_Names.getKAction());
  }

  public String GetFunction() {
      return GetAttribute(sml_Names.getKActionFunction());
  }

  public boolean IsTagAddWme() {
      return IsTag(sml_Names.getKTagWMEAdd());
  }

  public boolean IsTagRemoveWme() {
      return IsTag(sml_Names.getKTagWMERemove());
  }

  public boolean IsTagWme() {
      return IsTag(sml_Names.getKTagWME());
  }

  public String GetWmeID() {
      return GetAttribute(sml_Names.getKWME_Id());
  }

  public String GetWmeAttribute() {
      return GetAttribute(sml_Names.getKWME_Attribute());
  }

  public String GetWmeValue() {
      return GetAttribute(sml_Names.getKWME_Value());
  }

  public String GetWmeTimeTag() {
      return GetAttribute(sml_Names.getKWME_TimeTag());
  }

  public String GetWmePreference() {
      return GetAttribute(sml_Names.getKWME_Preference());
  }

  public boolean IsTagPreference() {
      return IsTag(sml_Names.getKTagPreference());
  }

  public String GetPreferenceID() {
      return GetAttribute(sml_Names.getKWME_Id());
  }

  public String GetPreferenceAttribute() {
      return GetAttribute(sml_Names.getKWME_Attribute());
  }

  public String GetPreferenceValue() {
      return GetAttribute(sml_Names.getKWME_Value());
  }

  public String GetPreferenceType() {
      return GetAttribute(sml_Names.getKPreference_Type());
  }

  public String GetPreferenceTimeTag() {
      return GetAttribute(sml_Names.getKWME_TimeTag());
  }

  public String GetPreferenceOSupported() {
      return GetAttribute(sml_Names.getKOSupported());
  }

  public String GetPreferenceReferent() {
      return GetAttribute(sml_Names.getKReferent());
  }

  public boolean IsTagActionSideMarker() {
      return IsTag(sml_Names.getKTagActionSideMarker());
  }

  public boolean IsTagLocal() {
      return IsTag(sml_Names.getKTagLocal());
  }

  public boolean IsTagLocals() {
      return IsTag(sml_Names.getKTagLocals());
  }

  public boolean IsTagGrounds() {
      return IsTag(sml_Names.getKTagGrounds());
  }

  public boolean IsTagNegated() {
      return IsTag(sml_Names.getKTagNegated());
  }

  public boolean IsTagNot() {
      return IsTag(sml_Names.getKTagNot());
  }

  public boolean IsTagNots() {
      return IsTag(sml_Names.getKTagNots());
  }

  public boolean IsTagPotentials() {
      return IsTag(sml_Names.getKTagPotentials());
  }

  public boolean IsTagGroundedPotentials() {
      return IsTag(sml_Names.getKTagGroundedPotentials());
  }

  public boolean IsTagUngroundedPotentials() {
      return IsTag(sml_Names.getKTagUngroundedPotentials());
  }

  public boolean IsTagUngroundedPotential() {
      return IsTag(sml_Names.getKTagUngroundedPotential());
  }

  public boolean IsTagBacktrace() {
      return IsTag(sml_Names.getKTagBacktrace());
  }

  public boolean IsTagAddToPotentials() {
      return IsTag(sml_Names.getKTagAddToPotentials());
  }

  public boolean IsTagProhibitPreference() {
      return IsTag(sml_Names.getKTagProhibitPreference());
  }

  public boolean IsTagBacktraceResult() {
      return IsTag(sml_Names.getKTagBacktraceResult());
  }

  public boolean IsTagLocalNegation() {
      return IsTag(sml_Names.getKTagLocalNegation());
  }

  public String GetBacktraceAlreadyBacktraced() {
      return GetAttribute(sml_Names.getKBacktracedAlready());
  }

  public String GetBacktraceSymbol1() {
      return GetAttribute(sml_Names.getKBacktraceSymbol1());
  }

  public String GetBacktraceSymbol2() {
      return GetAttribute(sml_Names.getKBacktraceSymbol2());
  }

  public boolean IsTagCandidate() {
      return IsTag(sml_Names.getKTagCandidate());
  }

  public String GetCandidateName() {
      return GetAttribute(sml_Names.getKCandidateName());
  }

  public String GetCandidateType() {
      return GetAttribute(sml_Names.getKCandidateType());
  }

  public String GetCandidateValue() {
      return GetAttribute(sml_Names.getKCandidateValue());
  }

  public String GetCandidateExpValue() {
      return GetAttribute(sml_Names.getKCandidateExpValue());
  }

  public boolean IsTagError() {
      return IsTag(sml_Names.getKTagError());
  }

  public boolean IsTagWarning() {
      return IsTag(sml_Names.getKTagWarning());
  }

  public boolean IsTagMessage() {
      return IsTag(sml_Names.getKTagMessage());
  }

  public boolean IsTagVerbose() {
      return IsTag(sml_Names.getKTagVerbose());
  }

  public ClientTraceXML() {
  }

}
