/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.35
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package sml;

public class ClientErrors {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected ClientErrors(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ClientErrors obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      smlJNI.delete_ClientErrors(swigCPtr);
    }
    swigCPtr = 0;
  }

  public boolean HadError() {
    return smlJNI.ClientErrors_HadError(swigCPtr, this);
  }

  public String GetLastErrorDescription() {
    return smlJNI.ClientErrors_GetLastErrorDescription(swigCPtr, this);
  }

  public ClientErrors() {
    this(smlJNI.new_ClientErrors(), true);
  }

}
