/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.35
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package sml;

public class ClientTraceXML extends ClientXML {
  private long swigCPtr;

  protected ClientTraceXML(long cPtr, boolean cMemoryOwn) {
    super(smlJNI.SWIGClientTraceXMLUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ClientTraceXML obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      smlJNI.delete_ClientTraceXML(swigCPtr);
    }
    swigCPtr = 0;
    super.delete();
  }

  public boolean IsTagTrace() {
    return smlJNI.ClientTraceXML_IsTagTrace(swigCPtr, this);
  }

  public boolean IsTagRhsWrite() {
    return smlJNI.ClientTraceXML_IsTagRhsWrite(swigCPtr, this);
  }

  public String GetString() {
    return smlJNI.ClientTraceXML_GetString(swigCPtr, this);
  }

  public boolean IsTagState() {
    return smlJNI.ClientTraceXML_IsTagState(swigCPtr, this);
  }

  public String GetDecisionCycleCount() {
    return smlJNI.ClientTraceXML_GetDecisionCycleCount(swigCPtr, this);
  }

  public String GetStateID() {
    return smlJNI.ClientTraceXML_GetStateID(swigCPtr, this);
  }

  public String GetImpasseObject() {
    return smlJNI.ClientTraceXML_GetImpasseObject(swigCPtr, this);
  }

  public String GetImpasseType() {
    return smlJNI.ClientTraceXML_GetImpasseType(swigCPtr, this);
  }

  public String GetStackLevel() {
    return smlJNI.ClientTraceXML_GetStackLevel(swigCPtr, this);
  }

  public boolean IsTagOperator() {
    return smlJNI.ClientTraceXML_IsTagOperator(swigCPtr, this);
  }

  public String GetOperatorID() {
    return smlJNI.ClientTraceXML_GetOperatorID(swigCPtr, this);
  }

  public String GetOperatorName() {
    return smlJNI.ClientTraceXML_GetOperatorName(swigCPtr, this);
  }

  public boolean IsTagPhase() {
    return smlJNI.ClientTraceXML_IsTagPhase(swigCPtr, this);
  }

  public String GetPhaseName() {
    return smlJNI.ClientTraceXML_GetPhaseName(swigCPtr, this);
  }

  public String GetPhaseStatus() {
    return smlJNI.ClientTraceXML_GetPhaseStatus(swigCPtr, this);
  }

  public String GetFiringType() {
    return smlJNI.ClientTraceXML_GetFiringType(swigCPtr, this);
  }

  public String GetLevelNum() {
    return smlJNI.ClientTraceXML_GetLevelNum(swigCPtr, this);
  }

  public boolean IsTagSubphase() {
    return smlJNI.ClientTraceXML_IsTagSubphase(swigCPtr, this);
  }

  public boolean IsSubphaseNameFiringProductions() {
    return smlJNI.ClientTraceXML_IsSubphaseNameFiringProductions(swigCPtr, this);
  }

  public boolean IsSubphaseNameChangingWorkingMemory() {
    return smlJNI.ClientTraceXML_IsSubphaseNameChangingWorkingMemory(swigCPtr, this);
  }

  public boolean IsTagFiringProduction() {
    return smlJNI.ClientTraceXML_IsTagFiringProduction(swigCPtr, this);
  }

  public boolean IsTagRetractingProduction() {
    return smlJNI.ClientTraceXML_IsTagRetractingProduction(swigCPtr, this);
  }

  public boolean IsTagLearning() {
    return smlJNI.ClientTraceXML_IsTagLearning(swigCPtr, this);
  }

  public boolean IsTagProduction() {
    return smlJNI.ClientTraceXML_IsTagProduction(swigCPtr, this);
  }

  public String GetProductionName() {
    return smlJNI.ClientTraceXML_GetProductionName(swigCPtr, this);
  }

  public String GetProductionDoc() {
    return smlJNI.ClientTraceXML_GetProductionDoc(swigCPtr, this);
  }

  public String GetProductionType() {
    return smlJNI.ClientTraceXML_GetProductionType(swigCPtr, this);
  }

  public String GetProductionDeclaredSupport() {
    return smlJNI.ClientTraceXML_GetProductionDeclaredSupport(swigCPtr, this);
  }

  public boolean IsTagConditions() {
    return smlJNI.ClientTraceXML_IsTagConditions(swigCPtr, this);
  }

  public boolean IsTagCondition() {
    return smlJNI.ClientTraceXML_IsTagCondition(swigCPtr, this);
  }

  public boolean IsTagConjunctiveNegationCondition() {
    return smlJNI.ClientTraceXML_IsTagConjunctiveNegationCondition(swigCPtr, this);
  }

  public boolean IsTagActions() {
    return smlJNI.ClientTraceXML_IsTagActions(swigCPtr, this);
  }

  public boolean IsTagAction() {
    return smlJNI.ClientTraceXML_IsTagAction(swigCPtr, this);
  }

  public String GetConditionTest() {
    return smlJNI.ClientTraceXML_GetConditionTest(swigCPtr, this);
  }

  public String GetConditionId() {
    return smlJNI.ClientTraceXML_GetConditionId(swigCPtr, this);
  }

  public String GetCondition() {
    return smlJNI.ClientTraceXML_GetCondition(swigCPtr, this);
  }

  public String GetActionId() {
    return smlJNI.ClientTraceXML_GetActionId(swigCPtr, this);
  }

  public String GetAction() {
    return smlJNI.ClientTraceXML_GetAction(swigCPtr, this);
  }

  public String GetFunction() {
    return smlJNI.ClientTraceXML_GetFunction(swigCPtr, this);
  }

  public boolean IsTagAddWme() {
    return smlJNI.ClientTraceXML_IsTagAddWme(swigCPtr, this);
  }

  public boolean IsTagRemoveWme() {
    return smlJNI.ClientTraceXML_IsTagRemoveWme(swigCPtr, this);
  }

  public boolean IsTagWme() {
    return smlJNI.ClientTraceXML_IsTagWme(swigCPtr, this);
  }

  public String GetWmeID() {
    return smlJNI.ClientTraceXML_GetWmeID(swigCPtr, this);
  }

  public String GetWmeAttribute() {
    return smlJNI.ClientTraceXML_GetWmeAttribute(swigCPtr, this);
  }

  public String GetWmeValue() {
    return smlJNI.ClientTraceXML_GetWmeValue(swigCPtr, this);
  }

  public String GetWmeTimeTag() {
    return smlJNI.ClientTraceXML_GetWmeTimeTag(swigCPtr, this);
  }

  public String GetWmePreference() {
    return smlJNI.ClientTraceXML_GetWmePreference(swigCPtr, this);
  }

  public boolean IsTagPreference() {
    return smlJNI.ClientTraceXML_IsTagPreference(swigCPtr, this);
  }

  public String GetPreferenceID() {
    return smlJNI.ClientTraceXML_GetPreferenceID(swigCPtr, this);
  }

  public String GetPreferenceAttribute() {
    return smlJNI.ClientTraceXML_GetPreferenceAttribute(swigCPtr, this);
  }

  public String GetPreferenceValue() {
    return smlJNI.ClientTraceXML_GetPreferenceValue(swigCPtr, this);
  }

  public String GetPreferenceType() {
    return smlJNI.ClientTraceXML_GetPreferenceType(swigCPtr, this);
  }

  public String GetPreferenceTimeTag() {
    return smlJNI.ClientTraceXML_GetPreferenceTimeTag(swigCPtr, this);
  }

  public String GetPreferenceOSupported() {
    return smlJNI.ClientTraceXML_GetPreferenceOSupported(swigCPtr, this);
  }

  public String GetPreferenceReferent() {
    return smlJNI.ClientTraceXML_GetPreferenceReferent(swigCPtr, this);
  }

  public boolean IsTagActionSideMarker() {
    return smlJNI.ClientTraceXML_IsTagActionSideMarker(swigCPtr, this);
  }

  public boolean IsTagLocal() {
    return smlJNI.ClientTraceXML_IsTagLocal(swigCPtr, this);
  }

  public boolean IsTagLocals() {
    return smlJNI.ClientTraceXML_IsTagLocals(swigCPtr, this);
  }

  public boolean IsTagGrounds() {
    return smlJNI.ClientTraceXML_IsTagGrounds(swigCPtr, this);
  }

  public boolean IsTagNegated() {
    return smlJNI.ClientTraceXML_IsTagNegated(swigCPtr, this);
  }

  public boolean IsTagNot() {
    return smlJNI.ClientTraceXML_IsTagNot(swigCPtr, this);
  }

  public boolean IsTagNots() {
    return smlJNI.ClientTraceXML_IsTagNots(swigCPtr, this);
  }

  public boolean IsTagPotentials() {
    return smlJNI.ClientTraceXML_IsTagPotentials(swigCPtr, this);
  }

  public boolean IsTagGroundedPotentials() {
    return smlJNI.ClientTraceXML_IsTagGroundedPotentials(swigCPtr, this);
  }

  public boolean IsTagUngroundedPotentials() {
    return smlJNI.ClientTraceXML_IsTagUngroundedPotentials(swigCPtr, this);
  }

  public boolean IsTagUngroundedPotential() {
    return smlJNI.ClientTraceXML_IsTagUngroundedPotential(swigCPtr, this);
  }

  public boolean IsTagBacktrace() {
    return smlJNI.ClientTraceXML_IsTagBacktrace(swigCPtr, this);
  }

  public boolean IsTagAddToPotentials() {
    return smlJNI.ClientTraceXML_IsTagAddToPotentials(swigCPtr, this);
  }

  public boolean IsTagProhibitPreference() {
    return smlJNI.ClientTraceXML_IsTagProhibitPreference(swigCPtr, this);
  }

  public boolean IsTagBacktraceResult() {
    return smlJNI.ClientTraceXML_IsTagBacktraceResult(swigCPtr, this);
  }

  public boolean IsTagLocalNegation() {
    return smlJNI.ClientTraceXML_IsTagLocalNegation(swigCPtr, this);
  }

  public String GetBacktraceAlreadyBacktraced() {
    return smlJNI.ClientTraceXML_GetBacktraceAlreadyBacktraced(swigCPtr, this);
  }

  public String GetBacktraceSymbol1() {
    return smlJNI.ClientTraceXML_GetBacktraceSymbol1(swigCPtr, this);
  }

  public String GetBacktraceSymbol2() {
    return smlJNI.ClientTraceXML_GetBacktraceSymbol2(swigCPtr, this);
  }

  public boolean IsTagCandidate() {
    return smlJNI.ClientTraceXML_IsTagCandidate(swigCPtr, this);
  }

  public String GetCandidateName() {
    return smlJNI.ClientTraceXML_GetCandidateName(swigCPtr, this);
  }

  public String GetCandidateType() {
    return smlJNI.ClientTraceXML_GetCandidateType(swigCPtr, this);
  }

  public String GetCandidateValue() {
    return smlJNI.ClientTraceXML_GetCandidateValue(swigCPtr, this);
  }

  public String GetCandidateExpValue() {
    return smlJNI.ClientTraceXML_GetCandidateExpValue(swigCPtr, this);
  }

  public boolean IsTagError() {
    return smlJNI.ClientTraceXML_IsTagError(swigCPtr, this);
  }

  public boolean IsTagWarning() {
    return smlJNI.ClientTraceXML_IsTagWarning(swigCPtr, this);
  }

  public boolean IsTagMessage() {
    return smlJNI.ClientTraceXML_IsTagMessage(swigCPtr, this);
  }

  public boolean IsTagVerbose() {
    return smlJNI.ClientTraceXML_IsTagVerbose(swigCPtr, this);
  }

  public ClientTraceXML() {
    this(smlJNI.new_ClientTraceXML(), true);
  }

}
