/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.35
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package sml;

public class ElementXML {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected ElementXML(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ElementXML obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      smlJNI.delete_ElementXML(swigCPtr);
    }
    swigCPtr = 0;
  }

   public static final String kClassAttribute   = "Class" ;
   public static final String kVersionAttribute = "Version" ;

  public void addAttribute(String attributeName, String valueName) {
     AddAttribute(attributeName, valueName) ;
  }
  
	public String getAttributeThrows(String name) throws Exception {
		String value = GetAttribute(name) ;
		if (value == null)
			throw new Exception("Could not find attribute " + name + " while parsing XML document") ;			
		return value ;
	}  

	public int getAttributeIntThrows(String name) throws Exception {
		String val = getAttributeThrows(name) ;
		int intVal = Integer.parseInt(val) ;
		return intVal ;
	}
	
	private long GetCPtrAndDisown(ElementXML pChild) {
		pChild.swigCMemOwn = false;
		return ElementXML.getCPtr(pChild);
	}

  public static boolean IsValidID(String str) {
    return smlJNI.ElementXML_IsValidID(str);
  }

  public ElementXML() {
    this(smlJNI.new_ElementXML__SWIG_0(), true);
  }

  public ElementXML(SWIGTYPE_p_ElementXML_InterfaceStruct hXML) {
    this(smlJNI.new_ElementXML__SWIG_1(SWIGTYPE_p_ElementXML_InterfaceStruct.getCPtr(hXML)), true);
  }

  public int ReleaseRefOnHandle() {
    return smlJNI.ElementXML_ReleaseRefOnHandle(swigCPtr, this);
  }

  public int AddRefOnHandle() {
    return smlJNI.ElementXML_AddRefOnHandle(swigCPtr, this);
  }

  public int GetRefCount() {
    return smlJNI.ElementXML_GetRefCount(swigCPtr, this);
  }

  public void Attach(SWIGTYPE_p_ElementXML_InterfaceStruct hXML) {
    smlJNI.ElementXML_Attach(swigCPtr, this, SWIGTYPE_p_ElementXML_InterfaceStruct.getCPtr(hXML));
  }

  public SWIGTYPE_p_ElementXML_InterfaceStruct Detach() {
    long cPtr = smlJNI.ElementXML_Detach(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_ElementXML_InterfaceStruct(cPtr, false);
  }

  public SWIGTYPE_p_ElementXML_InterfaceStruct GetXMLHandle() {
    long cPtr = smlJNI.ElementXML_GetXMLHandle(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_ElementXML_InterfaceStruct(cPtr, false);
  }

  public boolean SetTagName(String tagName, boolean copyName) {
    return smlJNI.ElementXML_SetTagName__SWIG_0(swigCPtr, this, tagName, copyName);
  }

  public boolean SetTagName(String tagName) {
    return smlJNI.ElementXML_SetTagName__SWIG_1(swigCPtr, this, tagName);
  }

  public boolean SetTagNameConst(String tagName) {
    return smlJNI.ElementXML_SetTagNameConst(swigCPtr, this, tagName);
  }

  public String GetTagName() {
    return smlJNI.ElementXML_GetTagName(swigCPtr, this);
  }

  public boolean IsTag(String pTagName) {
    return smlJNI.ElementXML_IsTag(swigCPtr, this, pTagName);
  }

  public boolean SetComment(String pComment) {
    return smlJNI.ElementXML_SetComment(swigCPtr, this, pComment);
  }

  public String GetComment() {
    return smlJNI.ElementXML_GetComment(swigCPtr, this);
  }

  public SWIGTYPE_p_ElementXML_InterfaceStruct AddChild(ElementXML pChild) {
    long cPtr = smlJNI.ElementXML_AddChild(swigCPtr, this, GetCPtrAndDisown(pChild), pChild);
    return (cPtr == 0) ? null : new SWIGTYPE_p_ElementXML_InterfaceStruct(cPtr, false);
  }

  public int GetNumberChildren() {
    return smlJNI.ElementXML_GetNumberChildren(swigCPtr, this);
  }

  public boolean GetChild(ElementXML pChild, int index) {
    return smlJNI.ElementXML_GetChild(swigCPtr, this, GetCPtrAndDisown(pChild), pChild, index);
  }

  public boolean GetParent(ElementXML pParent) {
    return smlJNI.ElementXML_GetParent(swigCPtr, this, ElementXML.getCPtr(pParent), pParent);
  }

  public ElementXML MakeCopy() {
    long cPtr = smlJNI.ElementXML_MakeCopy(swigCPtr, this);
    return (cPtr == 0) ? null : new ElementXML(cPtr, false);
  }

  public boolean AddAttribute(String attributeName, String attributeValue, boolean copyName, boolean copyValue) {
    return smlJNI.ElementXML_AddAttribute__SWIG_0(swigCPtr, this, attributeName, attributeValue, copyName, copyValue);
  }

  public boolean AddAttribute(String attributeName, String attributeValue, boolean copyName) {
    return smlJNI.ElementXML_AddAttribute__SWIG_1(swigCPtr, this, attributeName, attributeValue, copyName);
  }

  public boolean AddAttribute(String attributeName, String attributeValue) {
    return smlJNI.ElementXML_AddAttribute__SWIG_2(swigCPtr, this, attributeName, attributeValue);
  }

  public boolean AddAttributeConst(String attributeName, String attributeValue) {
    return smlJNI.ElementXML_AddAttributeConst(swigCPtr, this, attributeName, attributeValue);
  }

  public boolean AddAttributeConstConst(String attributeName, String attributeValue) {
    return smlJNI.ElementXML_AddAttributeConstConst(swigCPtr, this, attributeName, attributeValue);
  }

  public int GetNumberAttributes() {
    return smlJNI.ElementXML_GetNumberAttributes(swigCPtr, this);
  }

  public String GetAttributeName(int index) {
    return smlJNI.ElementXML_GetAttributeName(swigCPtr, this, index);
  }

  public String GetAttributeValue(int index) {
    return smlJNI.ElementXML_GetAttributeValue(swigCPtr, this, index);
  }

  public String GetAttribute(String attName) {
    return smlJNI.ElementXML_GetAttribute(swigCPtr, this, attName);
  }

  public void SetCharacterData(String characterData, boolean copyData) {
    smlJNI.ElementXML_SetCharacterData__SWIG_0(swigCPtr, this, characterData, copyData);
  }

  public void SetCharacterData(String characterData) {
    smlJNI.ElementXML_SetCharacterData__SWIG_1(swigCPtr, this, characterData);
  }

  public void SetCharacterDataConst(String characterData) {
    smlJNI.ElementXML_SetCharacterDataConst(swigCPtr, this, characterData);
  }

  public void SetBinaryCharacterData(String characterData, int length, boolean copyData) {
    smlJNI.ElementXML_SetBinaryCharacterData__SWIG_0(swigCPtr, this, characterData, length, copyData);
  }

  public void SetBinaryCharacterData(String characterData, int length) {
    smlJNI.ElementXML_SetBinaryCharacterData__SWIG_1(swigCPtr, this, characterData, length);
  }

  public void SetBinaryCharacterDataConst(String characterData, int length) {
    smlJNI.ElementXML_SetBinaryCharacterDataConst(swigCPtr, this, characterData, length);
  }

  public String GetCharacterData() {
    return smlJNI.ElementXML_GetCharacterData(swigCPtr, this);
  }

  public boolean IsCharacterDataBinary() {
    return smlJNI.ElementXML_IsCharacterDataBinary(swigCPtr, this);
  }

  public boolean ConvertCharacterDataToBinary() {
    return smlJNI.ElementXML_ConvertCharacterDataToBinary(swigCPtr, this);
  }

  public int GetCharacterDataLength() {
    return smlJNI.ElementXML_GetCharacterDataLength(swigCPtr, this);
  }

  public void SetUseCData(boolean useCData) {
    smlJNI.ElementXML_SetUseCData(swigCPtr, this, useCData);
  }

  public boolean GetUseCData() {
    return smlJNI.ElementXML_GetUseCData(swigCPtr, this);
  }

  public String GenerateXMLString(boolean includeChildren, boolean insertNewLines) {
    return smlJNI.ElementXML_GenerateXMLString__SWIG_0(swigCPtr, this, includeChildren, insertNewLines);
  }

  public String GenerateXMLString(boolean includeChildren) {
    return smlJNI.ElementXML_GenerateXMLString__SWIG_1(swigCPtr, this, includeChildren);
  }

  public int DetermineXMLStringLength(boolean includeChildren, boolean insertNewLines) {
    return smlJNI.ElementXML_DetermineXMLStringLength__SWIG_0(swigCPtr, this, includeChildren, insertNewLines);
  }

  public int DetermineXMLStringLength(boolean includeChildren) {
    return smlJNI.ElementXML_DetermineXMLStringLength__SWIG_1(swigCPtr, this, includeChildren);
  }

  public static String AllocateString(int length) {
    return smlJNI.ElementXML_AllocateString(length);
  }

  public static void DeleteString(String pString) {
    smlJNI.ElementXML_DeleteString(pString);
  }

  public static String CopyString(String original) {
    return smlJNI.ElementXML_CopyString(original);
  }

  public static String CopyBuffer(String original, int length) {
    return smlJNI.ElementXML_CopyBuffer(original, length);
  }

  public static ElementXML ParseXMLFromString(String pString) {
    long cPtr = smlJNI.ElementXML_ParseXMLFromString(pString);
    return (cPtr == 0) ? null : new ElementXML(cPtr, true);
  }

  public static ElementXML ParseXMLFromStringSequence(String pString, long startPos, SWIGTYPE_p_size_t endPos) {
    long cPtr = smlJNI.ElementXML_ParseXMLFromStringSequence(pString, startPos, SWIGTYPE_p_size_t.getCPtr(endPos));
    return (cPtr == 0) ? null : new ElementXML(cPtr, false);
  }

  public static ElementXML ParseXMLFromFile(String pFilename) {
    long cPtr = smlJNI.ElementXML_ParseXMLFromFile(pFilename);
    return (cPtr == 0) ? null : new ElementXML(cPtr, true);
  }

  public static String GetLastParseErrorDescription() {
    return smlJNI.ElementXML_GetLastParseErrorDescription();
  }

}
