/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.35
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package sml;

public class EventHandlerPlusData {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected EventHandlerPlusData(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(EventHandlerPlusData obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      smlJNI.delete_EventHandlerPlusData(swigCPtr);
    }
    swigCPtr = 0;
  }

  public void setM_EventID(int value) {
    smlJNI.EventHandlerPlusData_m_EventID_set(swigCPtr, this, value);
  }

  public int getM_EventID() {
    return smlJNI.EventHandlerPlusData_m_EventID_get(swigCPtr, this);
  }

  public void setM_UserData(SWIGTYPE_p_void value) {
    smlJNI.EventHandlerPlusData_m_UserData_set(swigCPtr, this, SWIGTYPE_p_void.getCPtr(value));
  }

  public SWIGTYPE_p_void getM_UserData() {
    long cPtr = smlJNI.EventHandlerPlusData_m_UserData_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

  public void setM_CallbackID(int value) {
    smlJNI.EventHandlerPlusData_m_CallbackID_set(swigCPtr, this, value);
  }

  public int getM_CallbackID() {
    return smlJNI.EventHandlerPlusData_m_CallbackID_get(swigCPtr, this);
  }

  public EventHandlerPlusData() {
    this(smlJNI.new_EventHandlerPlusData__SWIG_0(), true);
  }

  public EventHandlerPlusData(int eventID, SWIGTYPE_p_void pData, int callbackID) {
    this(smlJNI.new_EventHandlerPlusData__SWIG_1(eventID, SWIGTYPE_p_void.getCPtr(pData), callbackID), true);
  }

  public int getEventID() {
    return smlJNI.EventHandlerPlusData_getEventID(swigCPtr, this);
  }

  public SWIGTYPE_p_void getUserData() {
    long cPtr = smlJNI.EventHandlerPlusData_getUserData(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

  public int getCallbackID() {
    return smlJNI.EventHandlerPlusData_getCallbackID(swigCPtr, this);
  }

}
