/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.35
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package sml;

public class Identifier extends WMElement {
  private long swigCPtr;

  protected Identifier(long cPtr, boolean cMemoryOwn) {
    super(smlJNI.SWIGIdentifierUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Identifier obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public synchronized void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      throw new UnsupportedOperationException("C++ destructor does not have public access");
    }
    swigCPtr = 0;
    super.delete();
  }

  public SWIGTYPE_p_std__listT_sml__WMElement_p_t__iterator GetChildrenBegin() {
    return new SWIGTYPE_p_std__listT_sml__WMElement_p_t__iterator(smlJNI.Identifier_GetChildrenBegin(swigCPtr, this), true);
  }

  public SWIGTYPE_p_std__listT_sml__WMElement_p_t__iterator GetChildrenEnd() {
    return new SWIGTYPE_p_std__listT_sml__WMElement_p_t__iterator(smlJNI.Identifier_GetChildrenEnd(swigCPtr, this), true);
  }

  public String GetValueType() {
    return smlJNI.Identifier_GetValueType(swigCPtr, this);
  }

  public String GetValueAsString() {
    return smlJNI.Identifier_GetValueAsString(swigCPtr, this);
  }

  public boolean IsIdentifier() {
    return smlJNI.Identifier_IsIdentifier(swigCPtr, this);
  }

  public Identifier ConvertToIdentifier() {
    long cPtr = smlJNI.Identifier_ConvertToIdentifier(swigCPtr, this);
    return (cPtr == 0) ? null : new Identifier(cPtr, false);
  }

  public WMElement FindFromTimeTag(int timeTag) {
    long cPtr = smlJNI.Identifier_FindFromTimeTag(swigCPtr, this, timeTag);
    return (cPtr == 0) ? null : new WMElement(cPtr, false);
  }

  public WMElement FindByAttribute(String pAttribute, int index) {
    long cPtr = smlJNI.Identifier_FindByAttribute(swigCPtr, this, pAttribute, index);
    return (cPtr == 0) ? null : new WMElement(cPtr, false);
  }

  public String GetParameterValue(String pAttribute) {
    return smlJNI.Identifier_GetParameterValue(swigCPtr, this, pAttribute);
  }

  public String GetCommandName() {
    return smlJNI.Identifier_GetCommandName(swigCPtr, this);
  }

  public void AddStatusComplete() {
    smlJNI.Identifier_AddStatusComplete(swigCPtr, this);
  }

  public void AddStatusError() {
    smlJNI.Identifier_AddStatusError(swigCPtr, this);
  }

  public void AddErrorCode(int errorCode) {
    smlJNI.Identifier_AddErrorCode(swigCPtr, this, errorCode);
  }

  public int GetNumberChildren() {
    return smlJNI.Identifier_GetNumberChildren(swigCPtr, this);
  }

  public WMElement GetChild(int index) {
    long cPtr = smlJNI.Identifier_GetChild(swigCPtr, this, index);
    return (cPtr == 0) ? null : new WMElement(cPtr, false);
  }

  public boolean AreChildrenModified() {
    return smlJNI.Identifier_AreChildrenModified(swigCPtr, this);
  }

}
