/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.35
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package sml;

public class IdentifierSymbol {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected IdentifierSymbol(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(IdentifierSymbol obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      smlJNI.delete_IdentifierSymbol(swigCPtr);
    }
    swigCPtr = 0;
  }

  public IdentifierSymbol(Identifier pIdentifier) {
    this(smlJNI.new_IdentifierSymbol(Identifier.getCPtr(pIdentifier), pIdentifier), true);
  }

  public String GetIdentifierSymbol() {
    return smlJNI.IdentifierSymbol_GetIdentifierSymbol(swigCPtr, this);
  }

  public void SetIdentifierSymbol(String pID) {
    smlJNI.IdentifierSymbol_SetIdentifierSymbol(swigCPtr, this, pID);
  }

  public boolean AreChildrenModified() {
    return smlJNI.IdentifierSymbol_AreChildrenModified(swigCPtr, this);
  }

  public void SetAreChildrenModified(boolean state) {
    smlJNI.IdentifierSymbol_SetAreChildrenModified(swigCPtr, this, state);
  }

  public void NoLongerUsedBy(Identifier pIdentifier) {
    smlJNI.IdentifierSymbol_NoLongerUsedBy(swigCPtr, this, Identifier.getCPtr(pIdentifier), pIdentifier);
  }

  public void UsedBy(Identifier pIdentifier) {
    smlJNI.IdentifierSymbol_UsedBy(swigCPtr, this, Identifier.getCPtr(pIdentifier), pIdentifier);
  }

  public boolean IsFirstUser(Identifier pIdentifier) {
    return smlJNI.IdentifierSymbol_IsFirstUser(swigCPtr, this, Identifier.getCPtr(pIdentifier), pIdentifier);
  }

  public Identifier GetFirstUser() {
    long cPtr = smlJNI.IdentifierSymbol_GetFirstUser(swigCPtr, this);
    return (cPtr == 0) ? null : new Identifier(cPtr, false);
  }

  public int GetNumberUsing() {
    return smlJNI.IdentifierSymbol_GetNumberUsing(swigCPtr, this);
  }

  public void AddChild(WMElement pWME) {
    smlJNI.IdentifierSymbol_AddChild(swigCPtr, this, WMElement.getCPtr(pWME), pWME);
  }

  public void DeleteAllChildren() {
    smlJNI.IdentifierSymbol_DeleteAllChildren(swigCPtr, this);
  }

  public void RemoveChild(WMElement pWME) {
    smlJNI.IdentifierSymbol_RemoveChild(swigCPtr, this, WMElement.getCPtr(pWME), pWME);
  }

}
