/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.35
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package sml;

public class PrintEventHandlerPlusData extends EventHandlerPlusData {
    
    Agent.PrintEventInterface m_Handler;
    boolean m_IgnoreOwnEchos;
    
    /*
  private long swigCPtr;

  protected PrintEventHandlerPlusData(long cPtr, boolean cMemoryOwn) {
    super(smlJNI.SWIGPrintEventHandlerPlusDataUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(PrintEventHandlerPlusData obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }
*/
  public synchronized void delete() {
      /*
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      smlJNI.delete_PrintEventHandlerPlusData(swigCPtr);
    }
    swigCPtr = 0;
    */
    super.delete();
  }

  public void setM_Handler(SWIGTYPE_p_f_enum_sml__smlPrintEventId_p_void_p_sml__Agent_p_q_const__char__void value) {
      throw new UnsupportedOperationException("Not implemented");
  }

  public SWIGTYPE_p_f_enum_sml__smlPrintEventId_p_void_p_sml__Agent_p_q_const__char__void getM_Handler() {
      throw new UnsupportedOperationException("Not implemented");
  }

  public void setM_IgnoreOwnEchos(boolean value) {
      throw new UnsupportedOperationException("Not implemented");
  }

  public boolean getM_IgnoreOwnEchos() {
      throw new UnsupportedOperationException("Not implemented");
  }

  public PrintEventHandlerPlusData() {
      throw new UnsupportedOperationException("Not implemented");
  }

  public PrintEventHandlerPlusData(int eventID, SWIGTYPE_p_f_enum_sml__smlPrintEventId_p_void_p_sml__Agent_p_q_const__char__void handler, SWIGTYPE_p_void userData, boolean ignoreOwnEchos, int callbackID) {
      throw new UnsupportedOperationException("Not implemented");
  }

}
