/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.35
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package sml;

public enum smlAgentEventId {
  smlEVENT_AFTER_AGENT_CREATED(smlProductionEventId.smlEVENT_LAST_PRODUCTION_EVENT.swigValue() + 1),
  smlEVENT_BEFORE_AGENT_DESTROYED,
  smlEVENT_BEFORE_AGENT_REINITIALIZED,
  smlEVENT_AFTER_AGENT_REINITIALIZED,
  smlEVENT_LAST_AGENT_EVENT(smlEVENT_AFTER_AGENT_REINITIALIZED);

  public final int swigValue() {
    return swigValue;
  }

  public static smlAgentEventId swigToEnum(int swigValue) {
    smlAgentEventId[] swigValues = smlAgentEventId.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (smlAgentEventId swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + smlAgentEventId.class + " with value " + swigValue);
  }

  private smlAgentEventId() {
    this.swigValue = SwigNext.next++;
  }

  private smlAgentEventId(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  private smlAgentEventId(smlAgentEventId swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

