/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.35
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package sml;

public enum smlPrintEventId {
  smlEVENT_ECHO(smlWorkingMemoryEventId.smlEVENT_LAST_WM_EVENT.swigValue() + 1),
  smlEVENT_FIRST_PRINT_EVENT(smlEVENT_ECHO),
  smlEVENT_PRINT,
  smlEVENT_LAST_PRINT_EVENT(smlEVENT_PRINT);

  public final int swigValue() {
    return swigValue;
  }

  public static smlPrintEventId swigToEnum(int swigValue) {
    smlPrintEventId[] swigValues = smlPrintEventId.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (smlPrintEventId swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + smlPrintEventId.class + " with value " + swigValue);
  }

  private smlPrintEventId() {
    this.swigValue = SwigNext.next++;
  }

  private smlPrintEventId(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  private smlPrintEventId(smlPrintEventId swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

