/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.35
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package sml;

public enum smlRunStepSize {
  sml_PHASE,
  sml_ELABORATION,
  sml_DECISION,
  sml_UNTIL_OUTPUT;

  public final int swigValue() {
    return swigValue;
  }

  public static smlRunStepSize swigToEnum(int swigValue) {
    smlRunStepSize[] swigValues = smlRunStepSize.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (smlRunStepSize swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + smlRunStepSize.class + " with value " + swigValue);
  }

  private smlRunStepSize() {
    this.swigValue = SwigNext.next++;
  }

  private smlRunStepSize(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  private smlRunStepSize(smlRunStepSize swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

