/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.35
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package sml;

public enum smlRunFlags {
  sml_NONE(0),
  sml_RUN_SELF(1 << 0),
  sml_RUN_ALL(1 << 1),
  sml_UPDATE_WORLD(1 << 2),
  sml_DONT_UPDATE_WORLD(1 << 3);

  public final int swigValue() {
    return swigValue;
  }

  public static smlRunFlags swigToEnum(int swigValue) {
    smlRunFlags[] swigValues = smlRunFlags.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (smlRunFlags swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + smlRunFlags.class + " with value " + swigValue);
  }

  private smlRunFlags() {
    this.swigValue = SwigNext.next++;
  }

  private smlRunFlags(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  private smlRunFlags(smlRunFlags swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

