/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.35
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package sml;

public enum smlRhsEventId {
  smlEVENT_RHS_USER_FUNCTION(smlPrintEventId.smlEVENT_LAST_PRINT_EVENT.swigValue() + 1),
  smlEVENT_FILTER,
  smlEVENT_CLIENT_MESSAGE,
  smlEVENT_LAST_RHS_EVENT(smlEVENT_CLIENT_MESSAGE);

  public final int swigValue() {
    return swigValue;
  }

  public static smlRhsEventId swigToEnum(int swigValue) {
    smlRhsEventId[] swigValues = smlRhsEventId.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (smlRhsEventId swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + smlRhsEventId.class + " with value " + swigValue);
  }

  private smlRhsEventId() {
    this.swigValue = SwigNext.next++;
  }

  private smlRhsEventId(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  private smlRhsEventId(smlRhsEventId swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

