/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.35
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package sml;

public enum smlUpdateEventId {
  smlEVENT_AFTER_ALL_OUTPUT_PHASES(smlXMLEventId.smlEVENT_LAST_XML_EVENT.swigValue() + 1),
  smlEVENT_AFTER_ALL_GENERATED_OUTPUT,
  smlEVENT_LAST_UPDATE_EVENT(smlEVENT_AFTER_ALL_GENERATED_OUTPUT);

  public final int swigValue() {
    return swigValue;
  }

  public static smlUpdateEventId swigToEnum(int swigValue) {
    smlUpdateEventId[] swigValues = smlUpdateEventId.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (smlUpdateEventId swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + smlUpdateEventId.class + " with value " + swigValue);
  }

  @SuppressWarnings("unused")
  private smlUpdateEventId() {
    this.swigValue = SwigNext.next++;
  }

  @SuppressWarnings("unused")
  private smlUpdateEventId(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  @SuppressWarnings("unused")
  private smlUpdateEventId(smlUpdateEventId swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

