/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.35
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package sml;

public enum smlXMLEventId {
  smlEVENT_XML_TRACE_OUTPUT(smlRhsEventId.smlEVENT_LAST_RHS_EVENT.swigValue() + 1),
  smlEVENT_XML_INPUT_RECEIVED,
  smlEVENT_LAST_XML_EVENT(smlEVENT_XML_INPUT_RECEIVED);

  public final int swigValue() {
    return swigValue;
  }

  public static smlXMLEventId swigToEnum(int swigValue) {
    smlXMLEventId[] swigValues = smlXMLEventId.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (smlXMLEventId swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + smlXMLEventId.class + " with value " + swigValue);
  }

  @SuppressWarnings("unused")
  private smlXMLEventId() {
    this.swigValue = SwigNext.next++;
  }

  @SuppressWarnings("unused")
  private smlXMLEventId(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  @SuppressWarnings("unused")
  private smlXMLEventId(smlXMLEventId swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

