/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.35
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package sml;

public class StringElement extends WMElement {


    private String m_Value;
    
    StringElement(Agent agent, IdentifierSymbol parentSymbol, String pid, String attributeName, String value, int timeTag)
    {
        super(agent, parentSymbol, pid, attributeName, timeTag);
        this.m_Value = value;
    }
    StringElement(Agent agent, Identifier parent, String pid, String attributeName, String value, int timeTag)
    {
        super(agent, parent.GetSymbol(), pid, attributeName, timeTag);
        this.m_Value = value;
    }
  public synchronized void delete() {
  }

  public String GetValueType() {
      return sml_Names.getKTypeString();
  }

  public String GetValueAsString() {
      return m_Value;
  }

  public String GetValue() {
      return m_Value;
  }

  public StringElement ConvertToStringElement() {
      return this;
  }
  
  void SetValue(String pValue)
  {
      m_Value = pValue ;
  }

}
