/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.35
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package sml;

public class WMEFinder {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected WMEFinder(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(WMEFinder obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      smlJNI.delete_WMEFinder(swigCPtr);
    }
    swigCPtr = 0;
  }

  public WMEFinder(WMElement wme) {
    this(smlJNI.new_WMEFinder(WMElement.getCPtr(wme), wme), true);
  }

  public void setWme(WMElement value) {
    smlJNI.WMEFinder_wme_set(swigCPtr, this, WMElement.getCPtr(value), value);
  }

  public WMElement getWme() {
    long cPtr = smlJNI.WMEFinder_wme_get(swigCPtr, this);
    return (cPtr == 0) ? null : new WMElement(cPtr, false);
  }

}
