/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.35
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package sml;

public class WMElement {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected WMElement(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(WMElement obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public synchronized void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      throw new UnsupportedOperationException("C++ destructor does not have public access");
    }
    swigCPtr = 0;
  }

  public boolean IsJustAdded() {
    return smlJNI.WMElement_IsJustAdded(swigCPtr, this);
  }

  public IdentifierSymbol GetParent() {
    long cPtr = smlJNI.WMElement_GetParent(swigCPtr, this);
    return (cPtr == 0) ? null : new IdentifierSymbol(cPtr, false);
  }

  public IdentifierSymbol GetIdentifier() {
    long cPtr = smlJNI.WMElement_GetIdentifier(swigCPtr, this);
    return (cPtr == 0) ? null : new IdentifierSymbol(cPtr, false);
  }

  public String GetIdentifierName() {
    return smlJNI.WMElement_GetIdentifierName(swigCPtr, this);
  }

  public String GetAttribute() {
    return smlJNI.WMElement_GetAttribute(swigCPtr, this);
  }

  public String GetValueType() {
    return smlJNI.WMElement_GetValueType(swigCPtr, this);
  }

  public String GetValueAsString() {
    return smlJNI.WMElement_GetValueAsString(swigCPtr, this);
  }

  public int GetTimeTag() {
    return smlJNI.WMElement_GetTimeTag(swigCPtr, this);
  }

  public boolean IsIdentifier() {
    return smlJNI.WMElement_IsIdentifier(swigCPtr, this);
  }

  public Identifier ConvertToIdentifier() {
    long cPtr = smlJNI.WMElement_ConvertToIdentifier(swigCPtr, this);
    return (cPtr == 0) ? null : new Identifier(cPtr, false);
  }

  public IntElement ConvertToIntElement() {
    long cPtr = smlJNI.WMElement_ConvertToIntElement(swigCPtr, this);
    return (cPtr == 0) ? null : new IntElement(cPtr, false);
  }

  public FloatElement ConvertToFloatElement() {
    long cPtr = smlJNI.WMElement_ConvertToFloatElement(swigCPtr, this);
    return (cPtr == 0) ? null : new FloatElement(cPtr, false);
  }

  public StringElement ConvertToStringElement() {
    long cPtr = smlJNI.WMElement_ConvertToStringElement(swigCPtr, this);
    return (cPtr == 0) ? null : new StringElement(cPtr, false);
  }

  public Agent GetAgent() {
    long cPtr = smlJNI.WMElement_GetAgent(swigCPtr, this);
    return (cPtr == 0) ? null : new Agent(cPtr, false);
  }

}
