/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.35
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package sml;

public class XMLEventHandlerPlusData extends EventHandlerPlusData {
    /*
  private long swigCPtr;

  protected XMLEventHandlerPlusData(long cPtr, boolean cMemoryOwn) {
    super(smlJNI.SWIGXMLEventHandlerPlusDataUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(XMLEventHandlerPlusData obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }
*/
  public synchronized void delete() {
      /*
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      smlJNI.delete_XMLEventHandlerPlusData(swigCPtr);
    }
    swigCPtr = 0;
    */
    super.delete();
  }

  public void setM_Handler(SWIGTYPE_p_f_enum_sml__smlXMLEventId_p_void_p_sml__Agent_p_sml__ClientXML__void value) {
      throw new UnsupportedOperationException("Not implemented");
  }

  public SWIGTYPE_p_f_enum_sml__smlXMLEventId_p_void_p_sml__Agent_p_sml__ClientXML__void getM_Handler() {
      throw new UnsupportedOperationException("Not implemented");
  }

  public XMLEventHandlerPlusData() {
      throw new UnsupportedOperationException("Not implemented");
  }

  public XMLEventHandlerPlusData(int eventID, SWIGTYPE_p_f_enum_sml__smlXMLEventId_p_void_p_sml__Agent_p_sml__ClientXML__void handler, SWIGTYPE_p_void userData, int callbackID) {
      throw new UnsupportedOperationException("Not implemented");
  }

}
