@startuml

!include stylesheet.iuml

class SoarReteListener

class Decider

class IdentifierImpl implements Identifier
class SymbolImpl
interface Identifier

class GoalIndentifierInfo

IdentifierImpl --|> SymbolImpl
IdentifierImpl --> GoalIndentifierInfo : goalInfo

SoarReteListener --> Decider

Decider --> IdentifierImpl : topGoal
Decider --> IdentifierImpl : bottomGoal
@enduml