@startuml

!include stylesheet.iuml

class Agent

class DecisionCycle
class Decider

class GoalIdentifierInfo

interface Identifier
class IdentifierImpl implements Identifier
class InputOutputImpl

class SoarReteListener
class SymbolImpl

Agent -> DecisionCycle

Decider --> IdentifierImpl : topGoal
Decider --> IdentifierImpl : bottomGoal

DecisionCycle -> Decider

IdentifierImpl --|> SymbolImpl
IdentifierImpl --> GoalIdentifierInfo : goalInfo

DecisionCycle --> InputOutputImpl
SoarReteListener --> Decider

@enduml